# Generated by Django 3.2.2 on 2021-05-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210517_1549'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='project_admin', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='admin',
            name='site',
            field=models.ManyToManyField(blank=True, related_name='site_admin', to='projects.Site'),
        ),
    ]
