# Generated by Django 3.2.2 on 2021-05-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210516_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='account_name',
            field=models.CharField(max_length=20),
        ),
    ]
