# Generated by Django 3.2.2 on 2021-05-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='site',
            name='admin',
        ),
    ]
