# Generated by Django 3.2.2 on 2021-05-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('Stone', '돌'), ('Iron', '철'), ('Waste', '폐기물'), ('Sand', '모래'), ('Soil', '흙')], max_length=20),
        ),
    ]
