# Generated by Django 3.2.2 on 2021-05-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('Stone', '돌'), ('Iron', '철'), ('Waste', '폐기물'), ('Dirt', '사토')], max_length=20),
        ),
    ]
