# Generated by Django 3.2.2 on 2021-05-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverecord',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='driverecord',
            name='total_distance',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='driverecord',
            name='unloading_time',
            field=models.DateTimeField(null=True),
        ),
    ]
