# Generated by Django 3.2.2 on 2021-05-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_driveroute_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveroute',
            name='distance',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
