# Generated by Django 3.2.2 on 2021-05-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('records', '0003_alter_driveroute_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverecord',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.driver'),
        ),
    ]
